# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='название')),
            ],
            options={
                'verbose_name_plural': 'города',
                'verbose_name': 'город',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='наименование')),
            ],
            options={
                'verbose_name_plural': 'страны',
                'verbose_name': 'страна',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(null=True, verbose_name='дата отправки')),
                ('arrival_time', models.DateTimeField(null=True, verbose_name='дата прибытия')),
                ('arrival_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_to', to='tour.City', verbose_name='место прибытия')),
                ('departure_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_from', to='tour.City', verbose_name='место отправки')),
            ],
            options={
                'verbose_name_plural': 'рейсы',
                'verbose_name': 'рейс',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True, verbose_name='стоимость')),
                ('flight_from', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_out_tour', to='tour.Flight', verbose_name='рейс оттуда')),
                ('flight_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_tour', to='tour.Flight', verbose_name='рейс туда')),
            ],
            options={
                'verbose_name_plural': 'туры',
                'verbose_name': 'тур',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.Country', verbose_name='страна'),
        ),
    ]
